title: QOlm
description: QAbstractListModel subclass that provide as List Model of QObject subclass to C++ and JS.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Olivier LDff
repo_url: "https://github.com/OlivierLDff/QOlm"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
