include(ProcessorCount)
ProcessorCount(N)
if(N EQUAL 0)
  set(PARALLEL_LEVEL "")
else()
  set(PARALLEL_LEVEL "-j${N}")
endif()

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Release")
endif()

if(Qt5_VERSION)
  set(QT_VERSION ${Qt5_VERSION})
else()
  set(QT_VERSION ${Qt6_VERSION})
endif()

message(STATUS " ")
message(STATUS "Versions:")
message(STATUS "  QOlm           : ${QOLM_VERSION} ${QOLM_TAG}")
message(STATUS "  Qt             : ${QT_VERSION}")

message(STATUS " ")
message(STATUS "Targets:")
message(STATUS "  QOlm           : cmake --build . --target ${QOLM_TARGET} --config ${CMAKE_BUILD_TYPE} ${PARALLEL_LEVEL}")

if(TARGET "${QOLM_TARGET}_Example")
message(STATUS " ")
message(STATUS "Example:")
message(STATUS "  QOlmExample    : cmake --build . --target ${QOLM_TARGET}_Example --config ${CMAKE_BUILD_TYPE} ${PARALLEL_LEVEL}")
message(STATUS "  QOlmExampleQml : cmake --build . --target ${QOLM_TARGET}_ExampleQml --config ${CMAKE_BUILD_TYPE} ${PARALLEL_LEVEL}")
endif()

if(TARGET "${QOLM_TARGET}_Tests")
message(STATUS " ")
message(STATUS "Tests:")
message(STATUS "  QOlmTests      : cmake --build . --target ${QOLM_TARGET}_Tests --config ${CMAKE_BUILD_TYPE} ${PARALLEL_LEVEL}")
message(STATUS "  QOlmTestsQml   : cmake --build . --target ${QOLM_TARGET}_TestsQml --config ${CMAKE_BUILD_TYPE} ${PARALLEL_LEVEL}")
message(STATUS "  Run Tests      : ctest -C ${CMAKE_BUILD_TYPE} . --verbose --progress")
endif()

if(${QOLM_ENABLE_INSTALL})
message(STATUS " ")
message(STATUS "Install to \"${CMAKE_INSTALL_PREFIX}\":")
message(STATUS "  Install        : cmake --install . [--prefix <install-dir>]")
endif()

message(STATUS " ")
